# Generated by Django 5.0.6 on 2024-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0002_rename_userregistration_userregistrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
