# Generated by Django 5.0.6 on 2024-06-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('topic', models.CharField(max_length=200)),
                ('trainer_name', models.CharField(max_length=100)),
            ],
        ),
    ]
