# Generated by Django 5.0.6 on 2024-06-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0006_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
